// <auto-generated />
using System;
using BLOC3ProjetReservationJO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BLOC3ProjetReservationJO.Migrations
{
    [DbContext(typeof(BLOC3ProjetReservationJOContext))]
    [Migration("20240508161739_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BLOC3ProjetReservationJO.Models.CommandModel", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CommandDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentKey")
                        .HasColumnType("uuid");

                    b.Property<string>("TicketKey")
                        .HasColumnType("text");

                    b.Property<Guid>("UserKey")
                        .HasColumnType("uuid");

                    b.HasKey("CommandId");

                    b.ToTable("CommandModel");
                });

            modelBuilder.Entity("BLOC3ProjetReservationJO.Models.EventModel", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PlaceAvailable")
                        .HasColumnType("integer");

                    b.Property<int>("SportName")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.ToTable("EventModel");
                });

            modelBuilder.Entity("BLOC3ProjetReservationJO.Models.OfferModel", b =>
                {
                    b.Property<Guid>("OfferKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventKey")
                        .HasColumnType("uuid");

                    b.Property<int>("Offer")
                        .HasColumnType("integer");

                    b.Property<int>("OfferPrice")
                        .HasColumnType("integer");

                    b.HasKey("OfferKey");

                    b.ToTable("OfferModel");
                });

            modelBuilder.Entity("BLOC3ProjetReservationJO.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("UserConnected")
                        .HasColumnType("boolean");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<bool>("UserExists")
                        .HasColumnType("boolean");

                    b.Property<string>("UserFirstName")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("UserPassword")
                        .HasColumnType("text");

                    b.HasKey("UserKey");

                    b.ToTable("UserModel");
                });
#pragma warning restore 612, 618
        }
    }
}
